From Tetris Require Import T5 Notations.
From Tetris Require T1 T2 T3 T4 T1Proofs T2Proofs T3Proofs T4Proofs.
From Stdlib Require Import Lia PeanoNat ZArith.
Import T1(Piece, PW, Grid, Valid, ForbiddenGrid).
Import (notations) T1.

Module T1P := T1Proofs.
Module T2P := T2Proofs.
Module T3P := T3Proofs.
Module T4P := T4Proofs.

(* Note: Most of the following proofs were generated by an LLM, then corrected
and edited manually. *)

(* ========================================================================= *)
(* Generic helpers                                                           *)
(* ========================================================================= *)

Lemma OptionMapSomeInv : ∀ [A B : Type] (f : A → B) (o : option A) (b : B)
  (H : option_map f o = Some b),
  ∃ a, o = Some a.
Proof.
  intros; destruct o as [a |].
  - exists a; reflexivity.
  - discriminate H.
Qed.

Lemma OptionMapSome : ∀ [A B : Type] [f : A → B] [optA : option A] [b : B]
  (H1 : option_map f optA = Some b),
  ∃ a, optA = Some a ∧ f a = b.
Proof.
  intros.
  destruct optA as [a |].
  - Check (H1 : option_map f (Some a) = Some b).
    exists a.
    simpl in H1; inject H1; tauto.
  - Check (H1 : option_map f None = Some b).
    simpl in H1; discriminate H1.
Qed.

(* Every T4-forwarded T5 event has the shape
 * `option_map (UpdateShadowY s) (optS4)`; this is the unique place where shape
 * is unfolded. *)
Lemma UpdateShadowYStep : ∀ [s s' : State] [optS4 : option T4.State]
  (Hn : option_map (UpdateShadowY s) optS4 = Some s'),
  ∃ s4', optS4 = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros.
  destruct optS4 as [s4' |] eqn: E.
  - exists s4'; split; [ reflexivity | ].
    cbv beta iota in Hn.
    assert (L1 : s' = UpdateShadowY s s4') by (inject Hn; now symmetry).
    rewrite L1; unfold UpdateShadowY; split; reflexivity.
  - discriminate Hn.
Qed.


(* ========================================================================= *)
(* Fuel-sufficiency for ShadowYImpl                                          *)
(* ========================================================================= *)

(* ShadowYImpl only ever descends while Valid holds one step lower, and stops
 * the instant it doesn't. Stated on `i`-style fuel/position pairs, mirroring
 * T1Proofs' FilterFullLinesSpec: as long as fuel is large enough to reach the
 * floor 1-PW (ValidBelowFloor, T1Proofs.v), the search cannot run out of fuel
 * before it runs out of room to fall. Every conclusion below is therefore
 * unconditional on the value of fuel, only on it being large enough. *)
Lemma ShadowYImplSpec : ∀ (fuel : ℕ) (g : Grid) (pc : Piece) (y0 x0 pr0 : ℤ)
  (HTY : T1.Y g = 0)
  (HR : 0 ≤ pr0 < 4)
  (HV0 : Valid g pc (y0, x0) pr0 = true)
  (HF : y0 - Z.of_nat fuel ≤ 1 - PW),
  let y' := ShadowYImpl fuel g pc y0 x0 pr0 in
    y' ≤ y0
  ∧ Valid g pc (y', x0) pr0 = true
  ∧ Valid g pc (y' - 1, x0) pr0 = false
  ∧ (∀ y, y' < y ≤ y0 → Valid g pc (y, x0) pr0 = true).
Proof.
  induction fuel as [| fuel' IH]; intros g pc y0 x0 pr0 HTY HR HV0 HF; cbv zeta.
  - (* No fuel left: HF (at fuel=0) gives y0 ≤ 1-PW, and HV0 via the
     * contrapositive of ValidBelowFloor gives y0 ≥ 1-PW, so y0 = 1-PW exactly
     * and one step down is unconditionally invalid. *)
    assert (Hge : 1 - PW ≤ y0). {
      destruct (Z_lt_le_dec y0 (1 - PW)) as [Hlt | Hle]; [ | exact Hle ].
      exfalso; assert (Hc := T1P.ValidBelowFloor g pc y0 x0 pr0 HTY HR Hlt).
      rewrite Hc in HV0; discriminate HV0.
    }
    assert (Heq : y0 = 1 - PW). {
      keep_only HF Hge.
      change (Z.of_nat 0) with 0%Z in HF.
      lia.
    }
    assert (HV1 : Valid g pc (y0 - 1, x0) pr0 = false). {
      apply T1P.ValidBelowFloor; (exact HTY || exact HR || keep_only Heq; lia).
    }
    enough (y0 <= y0
          ∧ Valid g pc (y0, x0) pr0 = true
          ∧ Valid g pc (y0 - 1, x0) pr0 = false
          ∧ ∀ y : ℤ, y0 < y <= y0 → Valid g pc (y, x0) pr0 = true)
      by now cbn [ShadowYImpl].
    repeat split; try assumption; try (intros y Hy; exfalso; keep_only Hy); lia.
  - (* One unit of fuel: test one step down. *)
    destruct (Valid g pc (y0 - 1, x0) pr0) eqn: Hstep.
    + (* still valid one step down: recurse *)
      assert (Eeq : ShadowYImpl (S fuel') g pc y0 x0 pr0
                  = ShadowYImpl fuel' g pc (y0 - 1) x0 pr0). {
        cbn [ShadowYImpl]; rewrite Hstep; reflexivity.
      }
      assert (HF' : (y0 - 1) - Z.of_nat fuel' ≤ 1 - PW)
        by (keep_only HF; rewrite Nat2Z.inj_succ in HF; lia).
      set (I := IH g pc (y0 - 1) x0 pr0 HTY HR Hstep HF').
      assert (Hle : ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 <= y0 - 1)
        by now destruct I; tauto.
      assert (HVy' : Valid g pc (ShadowYImpl fuel' g pc (y0 - 1) x0 pr0, x0) pr0 = true)
        by now destruct I; tauto.
      assert (HVy'1 : Valid g pc (ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 - 1, x0) pr0 = false)
        by now destruct I; tauto.
      assert (Hall : ∀ y : ℤ, ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 < y <= y0 - 1 → Valid g pc (y, x0) pr0 = true)
        by now destruct I; tauto.
      cbv zeta in Hle, HVy', HVy'1, Hall.
      enough (
          ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 <= y0
        ∧ Valid g pc (ShadowYImpl fuel' g pc (y0 - 1) x0 pr0, x0) pr0 = true
        ∧ Valid g pc (ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 - 1, x0) pr0 = false
        ∧ ∀ y : ℤ, ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 < y <= y0 → Valid g pc (y, x0) pr0 = true)
        by now rewrite Eeq.
      assert (L1 : ∀ y : ℤ, ShadowYImpl fuel' g pc (y0 - 1) x0 pr0 < y <= y0
          → Valid g pc (y, x0) pr0 = true). {
        intros y Hy.
        destruct (Z.eq_dec y y0) as [Ey | Ey].
        - rewrite Ey; exact HV0.
        - apply Hall; keep_only Hy Ey; lia.
      }
      repeat split; (lia || exact HVy' || exact HVy'1 || apply L1).
    + (* not valid one step down: stop here *)
      assert (Eeq : ShadowYImpl (S fuel') g pc y0 x0 pr0 = y0). {
        cbn [ShadowYImpl]; rewrite Hstep; reflexivity.
      }
      enough (
          y0 <= y0
        ∧ Valid g pc (y0, x0) pr0 = true
        ∧ Valid g pc (y0 - 1, x0) pr0 = false
        ∧ ∀ y : ℤ, y0 < y <= y0 → Valid g pc (y, x0) pr0 = true)
        by now rewrite Eeq.
      repeat split; (lia || exact HV0 || exact Hstep ||
        (intros y Hy; exfalso; keep_only Hy; lia)).
Qed.

(* fuel = (Z.to_nat py) + (Z.to_nat PW) - 1 is always large enough to reach the
 * floor 1-PW: y0 - fuel ≤ 1-PW. When py ≥ 0 the fuel equals py+PW-1 exactly, so
 * y0-fuel = 1-PW (tight). When py < 0, Z.to_nat clamps py to 0, giving fuel
 * PW-1; then y0 - (PW-1) = py + 1 - PW ≤ 1 - PW since py < 0 (over-provisioned,
 * the search simply stops earlier when Valid fails). *)
Lemma ShadowYFuelSufficient : ∀ (py0 : ℤ),
  py0 - Z.of_nat (Z.to_nat py0 + Z.to_nat PW - 1) ≤ 1 - PW.
Proof.
  intro py0.
  assert (HPWpos : PW > 0) by (apply T1.AxiomsPW).
  assert (HPWnat : (1 <= Z.to_nat PW)%nat) by lia.
  destruct (Z_le_gt_dec 0 py0) as [Hpos | Hneg].
  - (* py0 ≥ 0: fuel = py0 + PW - 1 exactly, so y0 - fuel = 1 - PW. *)
    assert (Epy : Z.of_nat (Z.to_nat py0) = py0) by lia.
    assert (EPW : Z.of_nat (Z.to_nat PW) = PW) by lia.
    assert (Esub : Z.of_nat (Z.to_nat py0 + Z.to_nat PW - 1)
                 = Z.of_nat (Z.to_nat py0 + Z.to_nat PW) - 1)
      by (apply Nat2Z.inj_sub; lia).
    assert (Eadd : Z.of_nat (Z.to_nat py0 + Z.to_nat PW)
                 = Z.of_nat (Z.to_nat py0) + Z.of_nat (Z.to_nat PW))
      by (apply Nat2Z.inj_add).
    rewrite Esub, Eadd, Epy, EPW; lia.
  - (* py0 < 0: fuel = PW - 1, and py0 - (PW-1) ≤ 1 - PW because py0 ≤ 0. *)
    assert (Ezero : Z.to_nat py0 = 0%nat) by lia.
    assert (Efuel : Z.of_nat (Z.to_nat py0 + Z.to_nat PW - 1) = PW - 1). {
      rewrite Ezero, Nat.add_0_l.
      assert (E1 : Z.of_nat (Z.to_nat PW - 1) = Z.of_nat (Z.to_nat PW) - 1)
        by (apply Nat2Z.inj_sub; lia).
      assert (EPW : Z.of_nat (Z.to_nat PW) = PW) by lia.
      rewrite E1, EPW; reflexivity.
    }
    rewrite Efuel; keep_only Hneg; lia.
Qed.


(* ========================================================================= *)
(* ShadowY, assembled for an arbitrary T4 state                              *)
(* ========================================================================= *)

(* The piece is Valid at its own current position (mg,p,pyx,pr), whenever the
 * game is not over: PieceOccupiedInsideBounds holds unconditionally,
 * PieceOnFreeBlocks under `¬gameover`, and Valid is exactly their conjunction. *)
Lemma T1PieceValidNow : ∀ (s1 : T1.State)
  (Hc1 : T1.Correct s1)
  (Hgo1 : T1.gameover s1 = false),
  Valid (T1.mg s1) (T1.p s1) (T1.pyx s1) (T1.pr s1) = true.
Proof.
  intros s1 Hc1 Hgo1.
  assert (Hoib : T1.PieceOccupiedInsideBounds s1) by now apply T1P.CorrectSpec in Hc1; tauto.
  assert (Hofb : T1.PieceOnFreeBlocks s1) by now apply T1P.CorrectSpec in Hc1; tauto.
  unfold T1.PieceOccupiedInsideBounds in Hoib.
  unfold T1.PieceOnFreeBlocks in Hofb; specialize (Hofb Hgo1).
  unfold Valid; apply andb_true_iff; split; (exact Hoib || exact Hofb).
Qed.

Lemma ShadowYSpec : ∀ (s4' : T4.State)
  (Hc4 : T4.Correct s4')
  (Hgo : T4.gameover s4' = false),
    ShadowY s4' ≤ T4.py s4'
  ∧ Valid (T4.mg s4') (T4.p s4') (ShadowY s4', T4.px s4') (T4.pr s4') = true
  ∧ Valid (T4.mg s4') (T4.p s4') (ShadowY s4' - 1, T4.px s4') (T4.pr s4') = false
  ∧ (∀ y, y ≤ T4.py s4' →
      Valid (T4.mg s4') (T4.p s4') (y, T4.px s4') (T4.pr s4') = true →
      Valid (T4.mg s4') (T4.p s4') (y - 1, T4.px s4') (T4.pr s4') = false →
      y ≤ ShadowY s4').
Proof.
  intros s4' Hc4 Hgo.
  assert (Hc3 : T3.Correct (T4.s3 s4')) by now destruct Hc4; tauto.
  assert (Hc2 : T2.Correct (T3.s2 (T4.s3 s4'))) by now destruct Hc3; tauto.
  assert (Hc1 : T1.Correct (T2.s1 (T3.s2 (T4.s3 s4')))) by now destruct Hc2; tauto.
  (* mg/p/py/px/pr/gameover at T4 are, by definition, the corresponding T1
   * projections of the same underlying T1 state. *)
  assert (Emg : T4.mg s4' = T1.mg (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Ep : T4.p s4' = T1.p (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epy : T4.py s4' = T1.py (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epx : T4.px s4' = T1.px (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epr : T4.pr s4' = T1.pr (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Ego : T4.gameover s4' = T1.gameover (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  rewrite Ego in Hgo.
  assert (Epyx : T1.pyx (T2.s1 (T3.s2 (T4.s3 s4')))
               = (T4.py s4', T4.px s4')). {
    rewrite Epy, Epx; unfold T1.py, T1.px; apply surjective_pairing.
  }
  assert (HV0 : Valid (T4.mg s4') (T4.p s4') (T4.py s4', T4.px s4') (T4.pr s4') = true). {
    rewrite Emg, Ep, Epr; rewrite <- Epyx.
    apply T1PieceValidNow; [ exact Hc1 | exact Hgo ].
  }
  assert (HTY : T1.Y (T4.mg s4') = 0). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4'))))
      by now apply T1P.CorrectSpec in Hc1; tauto.
    assert (EYX1 : T1.YX (T1.mg (T2.s1 (T3.s2 (T4.s3 s4')))) = T1.YX T1.InitialMainGrid)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    assert (EYX0 : T1.YX T1.InitialMainGrid = (0, 0))
      by now pose proof T1.AxiomsInitialMainGrid; tauto.
    rewrite Emg; unfold T1.Y; rewrite EYX1, EYX0; reflexivity.
  }
  assert (HRpr : 0 ≤ T4.pr s4' < 4). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4'))))
      by now apply T1P.CorrectSpec in Hc1; tauto.
    assert (HPR : 0 <= T1.pr (T2.s1 (T3.s2 (T4.s3 s4'))) <= 3)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    rewrite Epr; keep_only HPR; lia.
  }
  unfold ShadowY.
  assert (HF := ShadowYFuelSufficient (T4.py s4')).
  destruct (ShadowYImplSpec (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
              (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')
              HTY HRpr HV0 HF)
    as (Hle & HVy' & HVy'1 & Hall).
  cbv zeta in Hle, HVy', HVy'1, Hall.
  repeat split.
  - exact Hle.
  - exact HVy'.
  - exact HVy'1.
  - intros y Hy1 Hy2 Hy3.
    destruct (Z_le_gt_dec y (ShadowYImpl (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
                              (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')))
      as [Hok | Hbad]; [ exact Hok | ].
    (* if y were strictly above the computed shadow, the spec says Valid(y-1)
     * would hold there — contradicting Hy3. *)
    exfalso.
    set (y' := ShadowYImpl (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
                 (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')) in *.
    assert (Hrange : y' < y ≤ T4.py s4') by (keep_only Hbad Hy1; lia).
    destruct (Z.eq_dec (y - 1) y') as [Eeq | Eneq].
    + rewrite Eeq in Hy3; rewrite HVy' in Hy3; discriminate Hy3.
    + assert (Hin : y' < y - 1 ≤ T4.py s4') by (keep_only Hrange Eneq; lia).
      assert (Hv := Hall (y - 1) Hin); rewrite Hv in Hy3; discriminate Hy3.
Qed.

Lemma T1PieceValidNowWithoutGameover : ∀ (s1 : T1.State)
  (Hc1 : T1.CorrectWithoutGameover s1)
  (Hgo1 : T1.gameover s1 = false),
  Valid (T1.mg s1) (T1.p s1) (T1.pyx s1) (T1.pr s1) = true.
Proof.
  intros s1 Hc1 Hgo1.
  assert (Hoib : T1.PieceOccupiedInsideBounds s1) by now destruct Hc1; tauto.
  assert (Hofb : T1.PieceOnFreeBlocks s1) by now destruct Hc1; tauto.
  unfold T1.PieceOccupiedInsideBounds in Hoib.
  unfold T1.PieceOnFreeBlocks in Hofb; specialize (Hofb Hgo1).
  unfold Valid; apply andb_true_iff; split; (exact Hoib || exact Hofb).
Qed.

(* Same as ShadowYSpec, but from CorrectWithoutGameover instead of full
Correct. T1PieceValidNow (hence this) never actually used the bidirectional
Gameover fact, only PieceOccupiedInsideBounds/PieceOnFreeBlocks (already in
CorrectWithoutGameover) plus not-gameover; GyEqShadowY never enters this
proof at all, it's purely a T5-level concept unrelated to ShadowY itself. *)
Lemma ShadowYSpecWithoutGameover : ∀ (s4' : T4.State)
  (Hc4 : T4.CorrectWithoutGameover s4')
  (Hgo : T4.gameover s4' = false),
    ShadowY s4' ≤ T4.py s4'
  ∧ Valid (T4.mg s4') (T4.p s4') (ShadowY s4', T4.px s4') (T4.pr s4') = true
  ∧ Valid (T4.mg s4') (T4.p s4') (ShadowY s4' - 1, T4.px s4') (T4.pr s4') = false
  ∧ (∀ y, y ≤ T4.py s4' →
      Valid (T4.mg s4') (T4.p s4') (y, T4.px s4') (T4.pr s4') = true →
      Valid (T4.mg s4') (T4.p s4') (y - 1, T4.px s4') (T4.pr s4') = false →
      y ≤ ShadowY s4').
Proof.
  intros s4' Hc4 Hgo.
  assert (Hc3 : T3.CorrectWithoutGameover (T4.s3 s4')) by now destruct Hc4; tauto.
  assert (Hc2 : T2.CorrectWithoutGameover (T3.s2 (T4.s3 s4'))) by now destruct Hc3; tauto.
  assert (Hc1 : T1.CorrectWithoutGameover (T2.s1 (T3.s2 (T4.s3 s4')))) by now destruct Hc2; tauto.
  assert (Emg : T4.mg s4' = T1.mg (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Ep : T4.p s4' = T1.p (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epy : T4.py s4' = T1.py (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epx : T4.px s4' = T1.px (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Epr : T4.pr s4' = T1.pr (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  assert (Ego : T4.gameover s4' = T1.gameover (T2.s1 (T3.s2 (T4.s3 s4')))) by reflexivity.
  rewrite Ego in Hgo.
  assert (Epyx : T1.pyx (T2.s1 (T3.s2 (T4.s3 s4')))
               = (T4.py s4', T4.px s4')). {
    rewrite Epy, Epx; unfold T1.py, T1.px; apply surjective_pairing.
  }
  assert (HV0 : Valid (T4.mg s4') (T4.p s4') (T4.py s4', T4.px s4') (T4.pr s4') = true). {
    rewrite Emg, Ep, Epr; rewrite <- Epyx.
    apply T1PieceValidNowWithoutGameover; [ exact Hc1 | exact Hgo ].
  }
  assert (HTY : T1.Y (T4.mg s4') = 0). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4'))))
      by now destruct Hc1; tauto.
    assert (EYX1 : T1.YX (T1.mg (T2.s1 (T3.s2 (T4.s3 s4')))) = T1.YX T1.InitialMainGrid)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    assert (EYX0 : T1.YX T1.InitialMainGrid = (0, 0))
      by now pose proof T1.AxiomsInitialMainGrid; tauto.
    rewrite Emg; unfold T1.Y; rewrite EYX1, EYX0; reflexivity.
  }
  assert (HRpr : 0 ≤ T4.pr s4' < 4). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4'))))
      by now destruct Hc1; tauto.
    assert (HPR : 0 <= T1.pr (T2.s1 (T3.s2 (T4.s3 s4'))) <= 3)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    rewrite Epr; keep_only HPR; lia.
  }
  unfold ShadowY.
  assert (HF := ShadowYFuelSufficient (T4.py s4')).
  destruct (ShadowYImplSpec (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
              (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')
              HTY HRpr HV0 HF)
    as (Hle & HVy' & HVy'1 & Hall).
  cbv zeta in Hle, HVy', HVy'1, Hall.
  repeat split.
  - exact Hle.
  - exact HVy'.
  - exact HVy'1.
  - intros y Hy1 Hy2 Hy3.
    destruct (Z_le_gt_dec y (ShadowYImpl (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
                              (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')))
      as [Hok | Hbad]; [ exact Hok | ].
    exfalso.
    set (y' := ShadowYImpl (Z.to_nat (T4.py s4') + Z.to_nat PW - 1)
                 (T4.mg s4') (T4.p s4') (T4.py s4') (T4.px s4') (T4.pr s4')) in *.
    assert (Hrange : y' < y ≤ T4.py s4') by (keep_only Hbad Hy1; lia).
    destruct (Z.eq_dec (y - 1) y') as [Eeq | Eneq].
    + rewrite Eeq in Hy3; rewrite HVy' in Hy3; discriminate Hy3.
    + assert (Hin : y' < y - 1 ≤ T4.py s4') by (keep_only Hrange Eneq; lia).
      assert (Hv := Hall (y - 1) Hin); rewrite Hv in Hy3; discriminate Hy3.
Qed.

Lemma NextT4EventUnchangedGy : ∀ [s s' optS4]
  (H1 : gy s = ShadowY (s4 s))
  (H2 : option_map (UpdateShadowY s) optS4 = Some s'),
  gy s' = ShadowY (s4 s').
Proof.
  intros.
  unfold option_map, UpdateShadowY in H2.
  destruct optS4.
  - inject H2.
    now rewrite <- H2.
  - discriminate H2.
Qed.


(* ========================================================================= *)
(* Helpers: what each event does to the two components of the state          *)
(* ========================================================================= *)

Lemma MovePieceStep : ∀ [s s' : State] [dyx]
  (Hn : MovePiece dyx s = Some s'),
  ∃ s4', T4.MovePiece dyx (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold MovePiece in Hn.
  exact (UpdateShadowYStep Hn).
Qed.

Lemma RotatePieceStep : ∀ [s s' : State] [cw]
  (Hn : RotatePiece cw s = Some s'),
  ∃ s4', T4.RotatePiece cw (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold RotatePiece in Hn.
  exact (UpdateShadowYStep Hn).
Qed.

(* A successful MovePiece proves T4's own guard held. *)
Lemma MovePieceNotGameover : ∀ [s s' dyx]
  (H1 : MovePiece dyx s = Some s'),
  gameover s = false.
Proof.
  intros.
  destruct (MovePieceStep H1) as [s4' [H2 _]].
  exact (T4P.MovePieceNotGameover H2).
Qed.

(* A successful RotatePiece proves T4's own guard held. *)
Lemma RotatePieceNotGameover : ∀ [s s' cw]
  (H1 : RotatePiece cw s = Some s'),
  gameover s = false.
Proof.
  intros.
  destruct (RotatePieceStep H1) as [s4' [H2 _]].
  exact (T4P.RotatePieceNotGameover H2).
Qed.

Lemma MovePieceMgGameoverUnchanged : ∀ [s s' dyx]
  (Hn : MovePiece dyx s = Some s'),
  mg s' = mg s ∧ gameover s' = gameover s.
Proof.
  intros.
  destruct (MovePieceStep Hn) as (s4' & E4 & Es4 & _).
  destruct (T4P.MovePieceMgGameoverUnchanged E4) as [Emg Ego].
  split.
  - unfold mg; rewrite Es4; exact Emg.
  - unfold gameover; rewrite Es4; exact Ego.
Qed.

Lemma RotatePieceMgGameoverUnchanged : ∀ [s s' cw]
  (Hn : RotatePiece cw s = Some s'),
  mg s' = mg s ∧ gameover s' = gameover s.
Proof.
  intros.
  destruct (RotatePieceStep Hn) as (s4' & E4 & Es4 & _).
  destruct (T4P.RotatePieceMgGameoverUnchanged E4) as [Emg Ego].
  split.
  - unfold mg; rewrite Es4; exact Emg.
  - unfold gameover; rewrite Es4; exact Ego.
Qed.

Lemma FixPieceStep : ∀ [s s' : State] [bagNew] [H : T4.PieceSet bagNew]
  (Hn : FixPiece bagNew H s = Some s'),
  ∃ s4', T4.FixPiece bagNew H (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold FixPiece in Hn.
  exact (UpdateShadowYStep Hn).
Qed.

Lemma HoldPieceStep : ∀ [s s' : State] [bagNew] [H : T4.PieceSet bagNew]
  (Hn : HoldPiece bagNew H s = Some s'),
  ∃ s4', T4.HoldPiece bagNew H (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold HoldPiece in Hn.
  exact (UpdateShadowYStep Hn).
Qed.

Lemma HoldPieceMgGameoverUnchanged : ∀ [bagNew] [H : T4.PieceSet bagNew] [s s']
  (Hn : HoldPiece bagNew H s = Some s'),
  mg s' = mg s ∧ gameover s' = gameover s.
Proof.
  intros.
  destruct (HoldPieceStep Hn) as (s4' & E4 & Es4 & _).
  destruct (T4P.HoldPieceMgGameoverUnchanged E4) as [Emg Ego].
  split.
  - unfold mg; rewrite Es4; exact Emg.
  - unfold gameover; rewrite Es4; exact Ego.
Qed.

Lemma StutterStep : ∀ [s s' : State]
  (Hg : GyEqShadowY s)
  (Hn : Next (Event4 T4.Stutter) s = Some s'),
  ∃ s4', T4.Next T4.Stutter (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros.
  assert (L1 : s = s') by now inject Hn.
  assert (L2 : GyEqShadowY s') by now rewrite L1 in Hg.
  exists (s4 s').
  enough (Some (s4 s) = Some (s4 s') ∧ s4 s' = s4 s' ∧ gy s' = ShadowY (s4 s')) by now simpl.
  rewrite L2.
  now rewrite L1.
Qed.

Lemma MovePieceFail : ∀ [s : State] [dyx]
  (Hn : MovePiece dyx s = None),
  T4.MovePiece dyx (s4 s) = None.
Proof.
  intros; unfold MovePiece, option_map in Hn.
  destruct (T4.MovePiece dyx (s4 s)) eqn: Hd; [ discriminate Hn | reflexivity ].
Qed.

Lemma FallStepStep : ∀ [s s' : State] [bagNew] [H : T4.PieceSet bagNew]
  (Hn : FallStep bagNew H s = Some s'),
  ∃ s4', T4.FallStep bagNew H (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold FallStep in Hn.
  destruct (MovePiece (-1, 0) s) as [t |] eqn: Hm in Hn.
  - assert (L1 : MovePiece (-1, 0)%Z s = Some s') by (rewrite Hm; exact Hn).
    destruct (MovePieceStep L1) as (s4' & E1 & E2 & E3).
    exists s4'; unfold T4.FallStep; rewrite E1.
    split; [ reflexivity | split; assumption ].
  - assert (L1 : T4.MovePiece (-1, 0)%Z (s4 s) = None) by (apply MovePieceFail; exact Hm).
    destruct (FixPieceStep Hn) as (s4' & E1 & E2 & E3).
    exists s4'; unfold T4.FallStep; rewrite L1, E1.
    split; [ reflexivity | split; assumption ].
Qed.

Lemma NextT4EventStep : ∀ [e4 : T4.Event] [s s' : State]
  (Hg : GyEqShadowY s)
  (Hn : NextT4Event e4 s = Some s'),
  ∃ s4', T4.Next e4 (s4 s) = Some s4' ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; destruct e4 as [dyx | cw | bagNew H | bagNew H | bagNew H |];
    unfold NextT4Event, T4.Next in *;
    exact (MovePieceStep Hn) || exact (RotatePieceStep Hn) ||
    exact (FixPieceStep Hn) || exact (FallStepStep Hn) ||
    exact (HoldPieceStep Hn) || exact (StutterStep Hg Hn).
Qed.

(* OptionMapSomeInv, applied at the T5→T4 boundary of DropPiece: `DropPiece`
 * calls FixPiece on a relocated state, so its success implies T4.FixPiece
 * succeeds there too. *)
Lemma DropPieceStep : ∀ [s s' : State] [bagNew] [H : T4.PieceSet bagNew]
  (Hn : DropPiece bagNew H s = Some s'),
  ∃ s4', T4.FixPiece bagNew H (s4 (NewPieceYXState (gy s, px s) s)) = Some s4'
       ∧ s4 s' = s4' ∧ gy s' = ShadowY s4'.
Proof.
  intros; unfold DropPiece, FixPiece in Hn.
  exact (UpdateShadowYStep Hn).
Qed.

(* T2.FixPiece forwards to T1.FixPiece under an option_map wrapper (score/level
 * bookkeeping only); its success therefore implies T1.FixPiece's does too, and
 * T1.FixPiece's own guard forces gameover=false. *)
Lemma FixPieceGuardGameover : ∀ [bagNew] [H : T4.PieceSet bagNew]
  [s4'' s4Result : T4.State]
  (Hn : T4.FixPiece bagNew H s4'' = Some s4Result),
  T4.gameover s4'' = false.
Proof.
  intros.
  assert (Hn3 : T3.FixPiece (T4.next s4'' 0) (T4.s3 s4'') = Some (T4.s3 s4Result))
    by (apply T4P.FixPieceStep in Hn as [E _]; exact E).
  assert (Hn2 : T2.FixPiece (T4.next s4'' 0) (T3.s2 (T4.s3 s4''))
              = Some (T3.s2 (T4.s3 s4Result)))
    by (apply T3P.FixPieceStep in Hn3 as [E _]; exact E).
  unfold T2.FixPiece in Hn2; cbv zeta in Hn2.
  apply OptionMapSomeInv in Hn2 as [s1Result Hn1].
  unfold T1.FixPiece in Hn1.
  destruct (! T1.gameover (T2.s1 (T3.s2 (T4.s3 s4''))) &&
            ! T1.CanMovePiece (-1, 0)%Z (T2.s1 (T3.s2 (T4.s3 s4'')))) eqn: Eg;
    [ | discriminate Hn1 ].
  apply andb_true_iff in Eg as [Eg1 _]; apply negb_true_iff in Eg1.
  unfold T4.gameover; exact Eg1.
Qed.

(* Same chain as FixPieceGuardGameover, but extracting the fresh-spawn facts
(p/pyx/pr) about the *output* state instead of the gameover guard on the
input. Needs OptionMapSome (not OptionMapSomeInv) since, unlike
FixPieceGuardGameover, this has to relate the witness s1Result back to the
actual output state's own s1 projection. *)
Lemma FixPieceFreshPieceT4 : ∀ [bagNew] [H : T4.PieceSet bagNew]
  [s4'' s4Result : T4.State]
  (Hn : T4.FixPiece bagNew H s4'' = Some s4Result),
  ∃ pNew,
    T1.p (T2.s1 (T3.s2 (T4.s3 s4Result))) = pNew
  ∧ T1.pyx (T2.s1 (T3.s2 (T4.s3 s4Result))) = T1.InitialYX pNew
  ∧ T1.pr (T2.s1 (T3.s2 (T4.s3 s4Result))) = 0.
Proof.
  intros.
  assert (Hn3 : T3.FixPiece (T4.next s4'' 0) (T4.s3 s4'') = Some (T4.s3 s4Result))
    by (apply T4P.FixPieceStep in Hn as [E _]; exact E).
  assert (Hn2 : T2.FixPiece (T4.next s4'' 0) (T3.s2 (T4.s3 s4''))
              = Some (T3.s2 (T4.s3 s4Result)))
    by (apply T3P.FixPieceStep in Hn3 as [E _]; exact E).
  unfold T2.FixPiece in Hn2; cbv zeta in Hn2.
  destruct (OptionMapSome Hn2) as [s1Result [Hn1 Es1]].
  exists (T4.next s4'' 0).
  destruct (T1P.FixPieceOK (T4.next s4'' 0) (T2.s1 (T3.s2 (T4.s3 s4''))) s1Result Hn1)
    as (_ & Ep & Epyx & Epr & _).
  assert (Es1' : T2.s1 (T3.s2 (T4.s3 s4Result)) = s1Result)
    by (rewrite <- Es1; reflexivity).
  rewrite Es1'.
  split; [exact Ep | split; [exact Epyx | exact Epr]].
Qed.

Lemma FixPieceFreshPiece : ∀ [s s' bagNew] [H : T4.PieceSet bagNew]
  (Hn : FixPiece bagNew H s = Some s'),
  ∃ pNew,
    T1.p (T2.s1 (T3.s2 (T4.s3 (s4 s')))) = pNew
  ∧ T1.pyx (T2.s1 (T3.s2 (T4.s3 (s4 s')))) = T1.InitialYX pNew
  ∧ T1.pr (T2.s1 (T3.s2 (T4.s3 (s4 s')))) = 0.
Proof.
  intros.
  destruct (FixPieceStep Hn) as (s4' & E4 & Es4 & _).
  rewrite Es4.
  exact (FixPieceFreshPieceT4 E4).
Qed.


(* ========================================================================= *)
(* State invariants                                                          *)
(* ========================================================================= *)

Lemma InitCorrect : ∀ (bags : ℕ → ℕ → Piece) (H : ∀ i, T4.PieceSet (bags i)),
  Correct (Init bags H).
Proof.
  intros.
  assert (Es4 : s4 (Init bags H) = T4.Init bags H) by reflexivity.
  assert (Egy : gy (Init bags H) = ShadowY (T4.Init bags H)) by reflexivity.
  assert (Hc4 : T4.Correct (T4.Init bags H)) by (apply T4P.InitCorrect).
  assert (L1 : T4.Correct (s4 (Init bags H)))
    by now rewrite Es4; exact Hc4.
  assert (L2 : LowestShadowY (Init bags H)). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover (T4.Init bags H) = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpec (T4.Init bags H) Hc4 Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg (Init bags H) = T4.mg (T4.Init bags H))
      by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p (Init bags H) = T4.p (T4.Init bags H))
      by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px (Init bags H) = T4.px (T4.Init bags H))
      by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr (Init bags H) = T4.pr (T4.Init bags H))
      by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py (Init bags H) = T4.py (T4.Init bags H))
      by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      (intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3))).
  }
  assert (L3 : GyEqShadowY (Init bags H))
    by now unfold GyEqShadowY, Init.
  unfold Correct; split_top; auto using L1, L2, L3.
Qed.

Lemma MovePieceCorrectWithoutGameover : ∀ [dyx s s']
  (Hc : CorrectWithoutGameover s)
  (Hn : MovePiece dyx s = Some s'),
  CorrectWithoutGameover s'.
Proof.
  intros.
  assert (L0 : T4.CorrectWithoutGameover (s4 s)) by now destruct Hc; tauto.
  destruct (MovePieceStep Hn) as (s4' & E4 & Es4 & Egy).
  assert (L2 : T4.CorrectWithoutGameover s4')
    by (eapply T4P.MovePieceCorrectWithoutGameover; (exact L0 || exact E4)).
  assert (L3 : T4.CorrectWithoutGameover (s4 s')) by now rewrite Es4; exact L2.
  assert (L4 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4' = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpecWithoutGameover s4' L2 Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg s' = T4.mg s4') by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4') by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4') by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4') by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4') by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3)).
  }
  assert (L5 : GyEqShadowY s'). {
    destruct (UpdateShadowYStep Hn) as (s4'' & _ & L5_1 & L5_2).
    Check (L5_1 : s4 s' = s4''). Check (L5_2 :gy s' = ShadowY s4'').
    rewrite <- L5_1 in L5_2.
    exact L5_2.
  }
  split; auto using L3, L4, L5.
Qed.

Lemma UpdateShadowYGuardGyEqShadowY : ∀ [s s' optS4]
  (H1 : option_map (UpdateShadowY s) optS4 = Some s'),
  GyEqShadowY s'.
Proof.
  intros.
  apply UpdateShadowYStep in H1 as (s4' & _ & L1 & L2).
  Check (L1 : s4 s' = s4'). Check (L2 : gy s' = ShadowY s4').
  congruence.
Qed.

Lemma RotatePieceCorrectWithoutGameover : ∀ [cw s s']
  (Hc : CorrectWithoutGameover s)
  (Hn : RotatePiece cw s = Some s'),
  CorrectWithoutGameover s'.
Proof.
  intros.
  assert (L0 : T4.CorrectWithoutGameover (s4 s)) by now destruct Hc; tauto.
  destruct (RotatePieceStep Hn) as (s4' & E4 & Es4 & Egy).
  assert (L2 : T4.CorrectWithoutGameover s4')
    by (eapply T4P.RotatePieceCorrectWithoutGameover; (exact L0 || exact E4)).
  assert (L3 : T4.CorrectWithoutGameover (s4 s')) by now rewrite Es4; exact L2.
  assert (L4 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4' = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpecWithoutGameover s4' L2 Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg s' = T4.mg s4') by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4') by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4') by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4') by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4') by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3)).
  }
  assert (L5 : GyEqShadowY s') by exact (UpdateShadowYGuardGyEqShadowY Hn).
  split; auto using L3, L4, L5.
Qed.

Lemma FixPieceCorrectWithoutGameover : ∀ [bagNew] [H : T4.PieceSet bagNew] [s s']
  (Hc : CorrectWithoutGameover s)
  (Hn : FixPiece bagNew H s = Some s'),
  CorrectWithoutGameover s'.
Proof.
  intros.
  assert (L0 : T4.CorrectWithoutGameover (s4 s)) by now destruct Hc; tauto.
  destruct (FixPieceStep Hn) as (s4' & E4 & Es4 & Egy).
  assert (L2 : T4.CorrectWithoutGameover s4')
    by (eapply T4P.FixPieceCorrectWithoutGameover; (exact L0 || exact E4)).
  assert (L3 : T4.CorrectWithoutGameover (s4 s')) by now rewrite Es4; exact L2.
  assert (L4 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4' = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpecWithoutGameover s4' L2 Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg s' = T4.mg s4') by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4') by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4') by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4') by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4') by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3)).
  }
  assert (L5 : GyEqShadowY s') by exact (UpdateShadowYGuardGyEqShadowY Hn).
  split; auto using L3, L4, L5.
Qed.

Lemma HoldPieceCorrectWithoutGameover : ∀ [bagNew] [H : T4.PieceSet bagNew] [s s']
  (Hc : CorrectWithoutGameover s)
  (Hg : ForbiddenGrid ∩ T1.mg (T2.s1 (T3.s2 (T4.s3 (s4 s)))) ⊈ ∅ = true
        → T1.gameover (T2.s1 (T3.s2 (T4.s3 (s4 s)))) = true)
  (Hn : HoldPiece bagNew H s = Some s'),
  CorrectWithoutGameover s'.
Proof.
  intros.
  assert (L0 : T4.CorrectWithoutGameover (s4 s)) by now destruct Hc; tauto.
  destruct (HoldPieceStep Hn) as (s4' & E4 & Es4 & Egy).
  assert (L2 : T4.CorrectWithoutGameover s4')
    by (eapply T4P.HoldPieceCorrectWithoutGameover; (exact L0 || exact Hg || exact E4)).
  assert (L3 : T4.CorrectWithoutGameover (s4 s')) by now rewrite Es4; exact L2.
  assert (L4 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4' = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpecWithoutGameover s4' L2 Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg s' = T4.mg s4') by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4') by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4') by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4') by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4') by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3)).
  }
  assert (L5 : GyEqShadowY s') by exact (UpdateShadowYGuardGyEqShadowY Hn).
  split; auto using L3, L4, L5.
Qed.

Lemma NextT4EventCorrect : ∀ [e4 s s']
  (Hc : Correct s)
  (Hn : NextT4Event e4 s = Some s'),
  Correct s'.
Proof.
  intros.
  assert (L0 : GyEqShadowY s) by now destruct Hc; tauto.
  destruct (NextT4EventStep L0 Hn) as (s4' & E4 & Es4 & Egy).
  assert (L1 : T4.Correct (s4 s)) by now unfold Correct in Hc; tauto.
  assert (L2 : T4.Correct s4') by (eapply T4P.NextCorrect; (exact L1 || exact E4)).
  assert (L3 : T4.Correct (s4 s')) by now rewrite Es4; exact L2.
  assert (L4 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4' = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpec s4' L2 Hgo') as (H1 & H2 & H3 & H4).
    (* Goal is LowestShadowY's body on s'; its mg/p/px/pr are T5 projections,
      * equal to T4.xx s4' via s4 s' = s4' (Es4). Rewrite them so H1..H4 apply. *)
    assert (Emg' : mg s' = T4.mg s4') by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4') by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4') by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4') by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4') by (unfold py; rewrite Es4; reflexivity).
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; (exact H1 || exact H2 || exact H3 ||
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3)).
  }
  assert (L5 : GyEqShadowY s'). {
    assert (L5_1 : gy s = ShadowY (s4 s))
      by now unfold Correct, GyEqShadowY in Hc; tauto.
    assert (L5_2 : ∀ [bagNew H] (Hf : FallStep bagNew H s = Some s'), GyEqShadowY s'). {
      intros; unfold FallStep in Hf.
      destruct (MovePiece (-1, 0) s) eqn: Hd in Hf.
      - rewrite Hf in Hd.
        apply (NextT4EventUnchangedGy L5_1 Hd).
      - apply (NextT4EventUnchangedGy L5_1 Hf).
    }
    assert (L5_3 : ∀ (Hs : Some s = Some s'), GyEqShadowY s')
      by now intros; inject Hs; rewrite <- Hs; exact L5_1.
    destruct e4 in Hn; simpl in Hn;
      (apply (NextT4EventUnchangedGy L5_1 Hn) || apply (L5_2 bagNew H Hn) || apply (L5_3 Hn)).
  }
  unfold Correct; split_top; auto using L3, L4, L5.
Qed.

Lemma DropPieceCorrect : ∀ [s s' bagNew] [H : T4.PieceSet bagNew]
  (Hc : Correct s)
  (Hm : DropPiece bagNew H s = Some s'),
  Correct s'.
Proof.
  intros.
  assert (Hc4 : T4.Correct (s4 s)) by now unfold Correct in Hc; tauto.
  (* Relocate to the shadow position, which is Valid by LowestShadowY,
    * provided the game is not already over; then FixPiece succeeding forces
    * exactly that (its own guard requires ¬gameover). *)
  destruct (DropPieceStep Hm) as (s4Res & E4 & Es4 & Egy).
  assert (Hgos : T4.gameover (s4 (NewPieceYXState (gy s, px s) s)) = false)
    by (apply (FixPieceGuardGameover E4)).
  assert (Egogo : T4.gameover (s4 (NewPieceYXState (gy s, px s) s)) = T4.gameover (s4 s))
    by reflexivity.
  rewrite Egogo in Hgos.
  (* From LowestShadowY s and ¬gameover s, the shadow position is Valid. *)
  assert (Hgos5 : gameover s = false) by (unfold gameover; exact Hgos).
  assert (HLow : LowestShadowY s) by now unfold Correct in Hc; tauto.
  unfold LowestShadowY in HLow; specialize (HLow Hgos5).
  assert (HVgy : ValidPieceCannotGoDown s (gy s))
    by now destruct HLow; tauto.
  unfold ValidPieceCannotGoDown in HVgy; destruct HVgy as [HVgy _].
  (* HVgy : Valid (mg s) (p s) (gy s, px s) (pr s) = true, where mg/p/px/pr are
    * the T5 projections, all equal by definition to the T1 ones. *)
  (* Reconstruct T4.Correct of the relocated state from T1's relocation lemma. *)
  assert (Hc1' : T1.Correct
            (T1.NewPieceYXState (gy s, px s) (T2.s1 (T3.s2 (T4.s3 (s4 s)))))). {
    apply T1P.NewPieceYXStateCorrect.
    - assert (Hc3 : T3.Correct (T4.s3 (s4 s))) by now destruct Hc4; tauto.
      assert (Hc2 : T2.Correct (T3.s2 (T4.s3 (s4 s)))) by now destruct Hc3; tauto.
      assert (Hc1 : T1.Correct (T2.s1 (T3.s2 (T4.s3 (s4 s))))) by now destruct Hc2; tauto.
      exact Hc1.
    - unfold mg, p, pr, px in HVgy.
      unfold T4.mg, T4.p, T4.pr, T4.px in HVgy.
      exact HVgy.
  }
  assert (Hc4'' : T4.Correct (s4 (NewPieceYXState (gy s, px s) s))). {
    (* Level/hold/swapped/Draw are all literally unchanged by the relocation,
      * at every intermediate layer. *)
    assert (Hc3 : T3.Correct (T4.s3 (s4 s))) by now destruct Hc4; tauto.
    assert (HCD : T4.CorrectD (T4.d (s4 s))) by now destruct Hc4; tauto.
    assert (Hc2 : T2.Correct (T3.s2 (T4.s3 (s4 s)))) by now destruct Hc3; tauto.
    assert (HSw : T3.SwappedImplyHoldSome (T4.s3 (s4 s))) by now destruct Hc3; tauto.
    assert (HGoNS : T3.GameoverImplyNotSwapped (T4.s3 (s4 s))) by now destruct Hc3; tauto.
    assert (HLv : T2.LevelCorrect (T3.s2 (T4.s3 (s4 s)))) by now destruct Hc2; tauto.
    unfold T4.Correct; split.
    - unfold T3.Correct; split; [ | split ];
      ((unfold T2.Correct; split; [ exact Hc1' | exact HLv ]) ||
      exact HSw || exact HGoNS).
    - exact HCD.
  }
  (* T4.FixPiece succeeding on this relocated, Correct state preserves T4.Correct.
    * T4.Next (T4.Fix bagNew H) s'' is convertible to T4.FixPiece bagNew H s''. *)
  assert (E4' : T4.Next (T4.Fix bagNew H) (s4 (NewPieceYXState (gy s, px s) s))
              = Some s4Res) by (exact E4).
  assert (Hc4Res : T4.Correct s4Res)
    by (eapply T4P.NextCorrect; (exact Hc4'' || exact E4')).
  assert (L1 : T4.Correct (s4 s'))
    by now rewrite Es4; exact Hc4Res.
  assert (L2 : LowestShadowY s'). {
    unfold LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4Res = false)
      by (unfold gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (ShadowYSpec s4Res Hc4Res Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : mg s' = T4.mg s4Res) by (unfold mg; rewrite Es4; reflexivity).
    assert (Ep' : p s' = T4.p s4Res) by (unfold p; rewrite Es4; reflexivity).
    assert (Epx' : px s' = T4.px s4Res) by (unfold px; rewrite Es4; reflexivity).
    assert (Epr' : pr s' = T4.pr s4Res) by (unfold pr; rewrite Es4; reflexivity).
    assert (Epy' : py s' = T4.py s4Res) by (unfold py; rewrite Es4; reflexivity).
    assert (L2_1 : ∀ y : ℤ,
        y <= T4.py s4Res
        → Valid (T4.mg s4Res) (T4.p s4Res) (y, T4.px s4Res) (T4.pr s4Res) =
        true
        ∧ Valid (T4.mg s4Res) (T4.p s4Res) (y - 1, T4.px s4Res)
        (T4.pr s4Res) = false → y <= ShadowY s4Res). {
      assert (L2_1_1 :
        ∀ y : ℤ, y <= T4.py s4Res
        → Valid (T4.mg s4Res) (T4.p s4Res) (y, T4.px s4Res) (T4.pr s4Res) = true
        → Valid (T4.mg s4Res) (T4.p s4Res) (y - 1, T4.px s4Res)
          (T4.pr s4Res) = false → y <= ShadowY s4Res)
          by now destruct (ShadowYSpec s4Res Hc4Res Hgo'); tauto.
      intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3).
    }
    unfold ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split; ((destruct (ShadowYSpec s4Res Hc4Res Hgo'); tauto) ||
      apply L2_1).
  }
  assert (L3 : GyEqShadowY s'). {
    assert (L3_1 : gy s = ShadowY (s4 s)) by now unfold Correct, GyEqShadowY in Hc; tauto.
    apply (NextT4EventUnchangedGy L3_1 Hm).
  }
  keep_only L1 L2 L3; unfold Correct; split_top; auto using L1, L2, L3.
Qed.

Lemma NextCorrect : ∀ [e : Event] [s s' : State]
  (Hc : Correct s)
  (Hn : Next e s = Some s'),
  Correct s'.
Proof.
  intros; destruct e; eauto using NextT4EventCorrect, DropPieceCorrect.
Qed.

Theorem SpecCorrect : ∀ e s s',
    (∀ bags H, Correct (Init bags H))
  ∧ (Correct s → Next e s = Some s' → Correct s').
Proof. split; eauto using InitCorrect, NextCorrect. Qed.


(* ========================================================================= *)
(* Step invariants                                                           *)
(* ========================================================================= *)

Theorem StepCorrect : ∀ [s] s'
  (Hc : Correct s),
  CorrectStep s s'.
Proof.
  intros.
  assert (L1 : T4.Correct (s4 s)) by now destruct Hc; tauto.
  split; apply (T4P.CorrectStepHold _ L1).
Qed.


(* ========================================================================= *)
(* Refinement                                                                *)
(* ========================================================================= *)

Lemma InitRefine : ∀ bags HSet,
  fₛ (Init bags HSet) = T4.Init bags HSet.
Proof. reflexivity. Qed.

(*
         e4
   s4    →    s4'
fₛ ↑     ⇑fₑ  ↑ fₛ
   s5    →    s5'
         e5
*)

Lemma NextRefine : ∀ e4 s5 s5'
  (H1 : GyEqShadowY s5)
  (H2 : NextT4Event e4 s5 = Some s5'),
  T4.Next (fₑ e4) (fₛ s5) = Some (fₛ s5').
Proof.
  intros.
  enough (T4.Next e4 (s4 s5) = Some (s4 s5')) by now unfold fₑ, fₛ, id.
  destruct (NextT4EventStep H1 H2) as [s4' H3].
  assert (E4 : T4.Next e4 (s4 s5) = Some s4') by now destruct H3; tauto.
  assert (Es4 : s4 s5' = s4') by now destruct H3; tauto.
  rewrite Es4; exact E4.
Qed.

Theorem T4RefinesT5Hold : T4RefinesT5.
Proof. split; auto using InitRefine, NextRefine. Qed.


(* ========================================================================= *)
(* Helpers for refining models                                               *)
(* ========================================================================= *)

Lemma MovePieceUnchangedGameover : ∀ [s s' dyx]
  (H1 : MovePiece dyx s = Some s'),
  gameover s' = gameover s.
Proof.
  intros.
  unfold MovePiece in H1.
  assert (L1 : ∃ s4', T4.MovePiece dyx (s4 s) = Some s4' ∧ UpdateShadowY s s4' = s')
    by now apply OptionMapSome in H1.
  destruct L1 as [s4' [E1 E2]].
  unfold T5.gameover; rewrite <- E2.
  exact (T4P.MovePieceUnchangedGameover E1).
Qed.

Lemma RotatePieceUnchangedGameover : ∀ [s s' cw]
  (H1 : RotatePiece cw s = Some s'),
  gameover s' = gameover s.
Proof.
  intros.
  unfold RotatePiece in H1.
  assert (L1 : ∃ s4', T4.RotatePiece cw (s4 s) = Some s4' ∧ UpdateShadowY s s4' = s')
    by now apply OptionMapSome in H1.
  destruct L1 as [s4' [E1 E2]].
  unfold gameover; rewrite <- E2.
  exact (T4P.RotatePieceUnchangedGameover E1).
Qed.

Lemma HoldPieceNotGameover : ∀ [s s' bagNew H]
  (H1 : HoldPiece bagNew H s = Some s'),
  gameover s = false.
Proof.
  intros.
  unfold HoldPiece in H1.
  assert (L1 : ∃ s4', T4.HoldPiece bagNew H (s4 s) = Some s4' ∧ UpdateShadowY s s4' = s')
    by now apply OptionMapSome in H1.
  destruct L1 as [s4' [E1 _]].
  unfold gameover; apply (T4P.HoldPieceStep E1).
Qed.

Lemma FixPieceNotGameover : ∀ [s s' bagNew H]
  (H1 : FixPiece bagNew H s = Some s'),
  gameover s = false.
Proof.
  intros.
  unfold FixPiece in H1.
  assert (L1 : ∃ s4', T4.FixPiece bagNew H (s4 s) = Some s4' ∧ UpdateShadowY s s4' = s')
    by now apply OptionMapSome in H1.
  destruct L1 as [s4' [E1 _]].
  unfold gameover; apply (FixPieceGuardGameover E1).
Qed.


(* Structural fact about ShadowYImpl: no hypothesis on Valid at the starting
position needed (this is a pure fact about the recursive definition). Either
the fuel-based search reaches a genuine stop (Valid fails one row further
down), or it consumes exactly the given fuel without ever finding one. *)
Lemma ShadowYImplStopsOrExhausts : ∀ (fuel : ℕ) (g : Grid) (pc : Piece) (y0 x0 pr0 : ℤ),
    Valid g pc (ShadowYImpl fuel g pc y0 x0 pr0 - 1, x0) pr0 = false
  ∨ ShadowYImpl fuel g pc y0 x0 pr0 = y0 - Z.of_nat fuel.
Proof.
  induction fuel as [| fuel' IH]; intros g pc y0 x0 pr0; simpl.
  - right; lia.
  - destruct (Valid g pc (y0 - 1, x0) pr0) eqn: Hstep; simpl.
    + destruct (IH g pc (y0 - 1) x0 pr0) as [IH1 | IH2].
      * left; exact IH1.
      * right; rewrite IH2; lia.
    + left; exact Hstep.
Qed.

(* ShadowY always finds a position it genuinely cannot descend from one more
row (regardless of whether the piece was itself Valid at py, i.e.
regardless of gameover). Only TypeOK-level facts are needed (always available
from CorrectWithoutGameover): if fuel runs out before a genuine stop,
ShadowYFuelSufficient says the search passed the floor 1-PW, and
ValidBelowFloor (itself HV0-free) forces invalidity there too. *)
Lemma ShadowYAlwaysStops : ∀ (s4 : T4.State)
  (Hc4 : T4.CorrectWithoutGameover s4),
  Valid (T4.mg s4) (T4.p s4) (ShadowY s4 - 1, T4.px s4) (T4.pr s4) = false.
Proof.
  intros s4 Hc4.
  assert (Hc3 : T3.CorrectWithoutGameover (T4.s3 s4)) by now destruct Hc4; tauto.
  assert (Hc2 : T2.CorrectWithoutGameover (T3.s2 (T4.s3 s4))) by now destruct Hc3; tauto.
  assert (Hc1 : T1.CorrectWithoutGameover (T2.s1 (T3.s2 (T4.s3 s4)))) by now destruct Hc2; tauto.
  assert (HTY : T1.Y (T4.mg s4) = 0). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4)))) by now destruct Hc1; tauto.
    assert (EYX1 : T1.YX (T1.mg (T2.s1 (T3.s2 (T4.s3 s4)))) = T1.YX T1.InitialMainGrid)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    assert (EYX0 : T1.YX T1.InitialMainGrid = (0, 0))
      by now pose proof T1.AxiomsInitialMainGrid; tauto.
    change (T4.mg s4) with (T1.mg (T2.s1 (T3.s2 (T4.s3 s4)))).
    unfold T1.Y; rewrite EYX1, EYX0; reflexivity.
  }
  assert (HRpr : 0 ≤ T4.pr s4 < 4). {
    assert (HT1 : T1.TypeOK (T2.s1 (T3.s2 (T4.s3 s4)))) by now destruct Hc1; tauto.
    assert (HPR : 0 <= T1.pr (T2.s1 (T3.s2 (T4.s3 s4))) <= 3)
      by now apply T1P.TypeOKSpec2 in HT1; tauto.
    keep_only HPR; unfold T4.pr; lia.
  }
  unfold ShadowY.
  destruct (ShadowYImplStopsOrExhausts (Z.to_nat (T4.py s4) + Z.to_nat PW - 1)
              (T4.mg s4) (T4.p s4) (T4.py s4) (T4.px s4) (T4.pr s4)) as [H | H].
  - exact H.
  - apply T1P.ValidBelowFloor; [exact HTY | exact HRpr | ].
    pose proof (ShadowYFuelSufficient (T4.py s4)) as Hle; lia.
Qed.

(* A stopped search is a no-op when restarted from its own result. *)
Lemma ShadowYImplNoOpWhenStopped : ∀ (fuel : ℕ) (g : Grid) (pc : Piece) (y x pr : ℤ),
  Valid g pc (y - 1, x) pr = false →
  ShadowYImpl fuel g pc y x pr = y.
Proof.
  intros fuel g pc y x pr H; destruct fuel as [| fuel']; simpl; [reflexivity |].
  rewrite H; reflexivity.
Qed.

(* ShadowY is idempotent: recomputing it from a state whose py is already
ShadowY s4 (and whose mg/p/pr/px agree with s4) gives back the same value.
No gameover hypothesis needed on either state. *)
Lemma ShadowYIdempotent : ∀ (s4 s4' : T4.State)
  (Hc4 : T4.CorrectWithoutGameover s4)
  (Emg : T4.mg s4' = T4.mg s4)
  (Ep  : T4.p  s4' = T4.p  s4)
  (Epr : T4.pr s4' = T4.pr s4)
  (Epx : T4.px s4' = T4.px s4)
  (Epy : T4.py s4' = ShadowY s4),
  ShadowY s4' = ShadowY s4.
Proof.
  intros s4 s4' Hc4 Emg Ep Epr Epx Epy.
  assert (Hstop := ShadowYAlwaysStops s4 Hc4).
  unfold ShadowY at 1.
  rewrite Emg, Ep, Epr, Epx, Epy.
  apply ShadowYImplNoOpWhenStopped; exact Hstop.
Qed.

Lemma ShadowYImplValidOrNoMove : ∀ (fuel : ℕ) (g : Grid) (pc : Piece) (y0 x0 pr0 : ℤ),
  ShadowYImpl fuel g pc y0 x0 pr0 = y0
  ∨ Valid g pc (ShadowYImpl fuel g pc y0 x0 pr0, x0) pr0 = true.
Proof.
  induction fuel as [| fuel' IH]; intros g pc y0 x0 pr0; simpl.
  - left; reflexivity.
  - destruct (Valid g pc (y0 - 1, x0) pr0) eqn: Hstep; simpl.
    + right.
      destruct (IH g pc (y0 - 1) x0 pr0) as [IH1 | IH2].
      * rewrite IH1; exact Hstep.
      * exact IH2.
    + left; reflexivity.
Qed.

Lemma ShadowYValidOrNoMove : ∀ (s4 : T4.State),
  ShadowY s4 = T4.py s4
  ∨ Valid (T4.mg s4) (T4.p s4) (ShadowY s4, T4.px s4) (T4.pr s4) = true.
Proof.
  intro s4; unfold ShadowY; apply ShadowYImplValidOrNoMove.
Qed.

(* T4-level version, same telescoping technique as FixPieceFreshPieceT4: chase
T1Proofs.FixPieceOK's gameover-accuracy conjunct (its 5th) up to the T4.FixPiece
result instead of extracting the fresh-piece facts (its 2nd-4th). *)
Lemma FixPieceGameoverEqT4 : ∀ [bagNew] [H : T4.PieceSet bagNew]
  [s4'' s4Result : T4.State]
  (Hn : T4.FixPiece bagNew H s4'' = Some s4Result),
  T1.gameover (T2.s1 (T3.s2 (T4.s3 s4Result)))
  = (ForbiddenGrid ∩ T1.mg (T2.s1 (T3.s2 (T4.s3 s4Result))) ⊈ ∅).
Proof.
  intros.
  assert (Hn3 : T3.FixPiece (T4.next s4'' 0) (T4.s3 s4'') = Some (T4.s3 s4Result))
    by (apply T4P.FixPieceStep in Hn as [E _]; exact E).
  assert (Hn2 : T2.FixPiece (T4.next s4'' 0) (T3.s2 (T4.s3 s4''))
              = Some (T3.s2 (T4.s3 s4Result)))
    by (apply T3P.FixPieceStep in Hn3 as [E _]; exact E).
  unfold T2.FixPiece in Hn2; cbv zeta in Hn2.
  destruct (OptionMapSome Hn2) as [s1Result [Hn1 Es1]].
  destruct (T1P.FixPieceOK (T4.next s4'' 0) (T2.s1 (T3.s2 (T4.s3 s4''))) s1Result Hn1)
    as (_ & _ & _ & _ & Ego).
  assert (Es1' : T2.s1 (T3.s2 (T4.s3 s4Result)) = s1Result)
    by (rewrite <- Es1; reflexivity).
  rewrite Es1'; exact Ego.
Qed.

(* T5-level wrapper: FixPiece = option_map (UpdateShadowY s) (T4.FixPiece ...),
so this transfers straight through FixPieceStep. Since T6.FixPiece/gameover/mg
are transparent aliases of T5's, this is usable at the T6 level as-is. *)
Lemma FixPieceGameoverEq : ∀ [bagNew] [H : T4.PieceSet bagNew] [s s' : State]
  (Hn : FixPiece bagNew H s = Some s'),
  gameover s' = (ForbiddenGrid ∩ mg s' ⊈ ∅).
Proof.
  intros.
  destruct (FixPieceStep Hn) as (s4' & E4 & Es4 & _).
  assert (Ego := FixPieceGameoverEqT4 E4).
  assert (Emg : mg s' = T1.mg (T2.s1 (T3.s2 (T4.s3 s4'))))
    by (unfold mg; rewrite Es4; reflexivity).
  assert (Egameover : gameover s' = T1.gameover (T2.s1 (T3.s2 (T4.s3 s4'))))
    by (unfold gameover; rewrite Es4; reflexivity).
  rewrite Egameover, Emg; exact Ego.
Qed.

(* T6.FixPiece always resets `swapped` to false, unconditionally. Needed
because NewMainGridGameoverState changes `gameover` but not `swapped`, so
GameoverImplyNotSwapped for the materialized state can't lean on s6''s own
invariant (whose antecedent is the *old*, single-player gameover flag, not
the multiplayer one). *)
Lemma FixPieceSwappedFalse : ∀ [bagNew] [H : T4.PieceSet bagNew] [s s' : State]
  (Hn : FixPiece bagNew H s = Some s'),
  T3.swapped (T4.s3 (s4 s')) = false.
Proof.
  intros.
  destruct (FixPieceStep Hn) as (s4' & E4 & Es4 & _).
  destruct (T4P.FixPieceStep E4) as (E3 & _).
  destruct (T3P.FixPieceStep E3) as (_ & _ & Esw).
  rewrite Es4; exact Esw.
Qed.