From Tetris Require Import T6 Notations.
From Tetris Require T1 T2 T3 T4 T5 T1Proofs T2Proofs T3Proofs T4Proofs T5Proofs.
From Stdlib Require Import Lia PeanoNat ZArith.

Module T1P := T1Proofs.
Module T2P := T2Proofs.
Module T3P := T3Proofs.
Module T4P := T4Proofs.
Module T5P := T5Proofs.

(* Note: Most of the following proofs were generated by an LLM, then corrected
and edited manually. *)


(* ========================================================================= *)
(* The core kick argument                                                    *)
(*                                                                            *)
(* Rotating after an arbitrary relocation preserves T5.Correct, by threading  *)
(* T1Proofs.RotateAfterRelocateCorrect up through T2-T5. Every layer's own    *)
(* extra invariant (LevelCorrect, SwappedImplyHoldSome/GameoverImplyNotSwapped, *)
(* CorrectD) is trivially preserved, since NewPieceYXState/RotatePiece never  *)
(* touch score/level/hold/swapped/Draw at any layer — mirroring exactly how   *)
(* T5Proofs.v's DropPiece case is assembled, except starting from the weaker  *)
(* TypeOK/Gameover/NoFullLine premise instead of a proof that the relocation  *)
(* target is already Valid (which, for a kick, is not known in advance).      *)
(* All T2-T5 projections/records are referenced fully qualified throughout,   *)
(* deliberately, to avoid the import-shadowing bug from T5Proofs.v.           *)
(* ========================================================================= *)

#[local] Ltac conjunct H := now destruct H; tauto.

Lemma RotateKickBranchGyEqShadowY : ∀ [pyxNew : ℤ × ℤ] [cw : bool] [s s' : T5.State]
  (Hc : T5.Correct s)
  (Hn : T5.RotatePiece cw (T5.NewPieceYXState pyxNew s) = Some s'),
  T5.GyEqShadowY s'.
Proof.
  intros.
  assert (L1 : T5.GyEqShadowY s) by conjunct Hc.
  apply (T5P.NextT4EventUnchangedGy L1 Hn).
Qed.

Lemma RotateKickBranchCorrectWithoutGameover : ∀ (pyxNew : ℤ × ℤ) (cw : bool) (s s' : T5.State)
  (Hc : T5.CorrectWithoutGameover s)
  (Hn : T5.RotatePiece cw (T5.NewPieceYXState pyxNew s) = Some s'),
  T5.CorrectWithoutGameover s' ∧ T5.mg s' = T5.mg s ∧ T5.gameover s' = T5.gameover s.
Proof.
  intros pyxNew cw s s' Hc Hn.
  assert (Hc4 : T4.CorrectWithoutGameover (T5.s4 s)) by now destruct Hc; tauto.
  destruct Hc4 as (Hc3 & HLow).
  destruct Hc3 as (Hc2 & HSw & HGoNS).
  destruct Hc2 as (Hc1 & HLv).
  set (s4o := T5.s4 s).
  set (s3o := T4.s3 s4o).
  set (s2o := T3.s2 s3o).
  set (s1o := T2.s1 s2o).
  destruct (T5P.RotatePieceStep Hn) as (s4res & E4 & Es4 & Egy).
  assert (Es4target : T5.s4 (T5.NewPieceYXState pyxNew s)
                     = T4.UnchangedT4Part s4o
                         (T3.UnchangedT3Part s3o
                           (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))))
    by reflexivity.
  rewrite Es4target in E4.
  destruct (T4P.RotatePieceStep E4) as (E3 & Ed).
  assert (Es3target : T4.s3 (T4.UnchangedT4Part s4o
                         (T3.UnchangedT3Part s3o
                           (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))))
                     = T3.UnchangedT3Part s3o
                         (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o)))
    by reflexivity.
  rewrite Es3target in E3.
  destruct (T3P.RotatePieceStep E3) as (E2 & Eh & Esw).
  assert (Es2target : T3.s2 (T3.UnchangedT3Part s3o
                         (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o)))
                     = T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))
    by reflexivity.
  rewrite Es2target in E2.
  destruct (T2P.RotatePieceStep E2) as (E1 & Esc & Elv & Ecb & Epc & Etc).
  assert (Es1target : T2.s1 (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))
                     = T1.NewPieceYXState pyxNew s1o)
    by reflexivity.
  rewrite Es1target in E1.
  symmetry in E1.
  destruct (T1P.RotateAfterRelocateCorrectWithoutGameover pyxNew cw s1o
              (T2.s1 (T3.s2 (T4.s3 s4res))) Hc1 E1) as (Hc1res & Ego1 & Emg1).
  assert (Elv' : T2.level (T3.s2 (T4.s3 s4res)) = T2.level s2o)
    by (rewrite Elv; reflexivity).
  assert (Etc' : T2.totalClearedLines (T3.s2 (T4.s3 s4res)) = T2.totalClearedLines s2o)
    by (rewrite Etc; reflexivity).
  assert (Hc2res : T2.CorrectWithoutGameover (T3.s2 (T4.s3 s4res))). {
    unfold T2.CorrectWithoutGameover; split.
    - exact Hc1res.
    - unfold T2.LevelCorrect; rewrite Elv', Etc'; exact HLv.
  }
  assert (Eh' : T3.hold (T4.s3 s4res) = T3.hold s3o) by (rewrite Eh; reflexivity).
  assert (Esw' : T3.swapped (T4.s3 s4res) = T3.swapped s3o) by (rewrite Esw; reflexivity).
  assert (Ego3 : T3.gameover (T4.s3 s4res) = T3.gameover s3o)
    by (unfold T3.gameover; rewrite Ego1; reflexivity).
  assert (Hc3res : T3.CorrectWithoutGameover (T4.s3 s4res)). {
    unfold T3.CorrectWithoutGameover; split; [ | split ].
    - exact Hc2res.
    - unfold T3.SwappedImplyHoldSome; rewrite Esw', Eh'; exact HSw.
    - unfold T3.GameoverImplyNotSwapped; rewrite Ego3, Esw'; exact HGoNS.
  }
  assert (Ed' : T4.d s4res = T4.d s4o) by (rewrite Ed; reflexivity).
  assert (Hc4res : T4.CorrectWithoutGameover s4res). {
    unfold T4.CorrectWithoutGameover; split.
    - exact Hc3res.
    - rewrite Ed'; exact HLow.
  }
  assert (Emg5 : T5.mg s' = T5.mg s)
    by (unfold T5.mg, T4.mg, T3.mg, T2.mg; rewrite Es4; exact Emg1).
  assert (Ego5 : T5.gameover s' = T5.gameover s)
    by (unfold T5.gameover, T4.gameover; rewrite Es4; exact Ego3).
  split; [ | split; [exact Emg5 | exact Ego5]].
  unfold T5.CorrectWithoutGameover; split_top.
  - rewrite Es4; exact Hc4res.
  - unfold T5.LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4res = false)
      by (unfold T5.gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (T5P.ShadowYSpecWithoutGameover s4res Hc4res Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : T5.mg s' = T4.mg s4res) by (unfold T5.mg; rewrite Es4; reflexivity).
    assert (Ep' : T5.p s' = T4.p s4res) by (unfold T5.p; rewrite Es4; reflexivity).
    assert (Epx' : T5.px s' = T4.px s4res) by (unfold T5.px; rewrite Es4; reflexivity).
    assert (Epr' : T5.pr s' = T4.pr s4res) by (unfold T5.pr; rewrite Es4; reflexivity).
    assert (Epy' : T5.py s' = T4.py s4res) by (unfold T5.py; rewrite Es4; reflexivity).
    unfold T5.ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split.
    + exact H1.
    + exact H2.
    + exact H3.
    + intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3).
  - exact (T5P.UpdateShadowYGuardGyEqShadowY Hn).
Qed.

Lemma RotateKickBranchCorrect : ∀ (pyxNew : ℤ × ℤ) (cw : bool) (s s' : T5.State)
  (Hc : T5.Correct s)
  (Hn : T5.RotatePiece cw (T5.NewPieceYXState pyxNew s) = Some s'),
  T5.Correct s'.
Proof.
  intros pyxNew cw s s' Hc Hn.
  (* assert (L1 : RotateKickBranchGyEqShadowY) *)
  assert (Hc4 : T4.Correct (T5.s4 s)) by now destruct Hc; tauto.
  assert (HLow : T5.LowestShadowY s ∧ T5.GyEqShadowY s) by now destruct Hc; tauto.
  destruct Hc4 as (Hc3 & HCD).
  destruct Hc3 as (Hc2 & HSw & HGoNS).
  destruct Hc2 as (Hc1 & HLv).
  destruct Hc1 as ((HT1 & _ & _ & HN1) & HG1).
  set (s4o := T5.s4 s).
  set (s3o := T4.s3 s4o).
  set (s2o := T3.s2 s3o).
  set (s1o := T2.s1 s2o).
  (* T5.RotatePiece forwards to T4 via UpdateShadowY. *)
  destruct (T5P.RotatePieceStep Hn) as (s4res & E4 & Es4 & Egy).
  assert (Es4target : T5.s4 (T5.NewPieceYXState pyxNew s)
                     = T4.UnchangedT4Part s4o
                         (T3.UnchangedT3Part s3o
                           (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))))
    by reflexivity.
  rewrite Es4target in E4.
  destruct (T4P.RotatePieceStep E4) as (E3 & Ed).
  assert (Es3target : T4.s3 (T4.UnchangedT4Part s4o
                         (T3.UnchangedT3Part s3o
                           (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))))
                     = T3.UnchangedT3Part s3o
                         (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o)))
    by reflexivity.
  rewrite Es3target in E3.
  destruct (T3P.RotatePieceStep E3) as (E2 & Eh & Esw).
  assert (Es2target : T3.s2 (T3.UnchangedT3Part s3o
                         (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o)))
                     = T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))
    by reflexivity.
  rewrite Es2target in E2.
  destruct (T2P.RotatePieceStep E2) as (E1 & Esc & Elv & Ecb & Epc & Etc).
  assert (Es1target : T2.s1 (T2.UnchangedT2Part s2o (T1.NewPieceYXState pyxNew s1o))
                     = T1.NewPieceYXState pyxNew s1o)
    by reflexivity.
  rewrite Es1target in E1.
  symmetry in E1.
  (* E1 : T1.RotatePiece cw (T1.NewPieceYXState pyxNew s1o)
        = Some (T2.s1 (T3.s2 (T4.s3 s4res))). *)
  destruct (T1P.RotateAfterRelocateCorrect pyxNew cw s1o (T2.s1 (T3.s2 (T4.s3 s4res)))
              HT1 HG1 HN1 E1) as (Hc1res & Ego1).
  (* T2.Correct: level/totalClearedLines are copied unchanged from s2o by
   * UnchangedT2Part, and preserved by T2P.RotatePieceStep. *)
  assert (Elv' : T2.level (T3.s2 (T4.s3 s4res)) = T2.level s2o)
    by (rewrite Elv; reflexivity).
  assert (Etc' : T2.totalClearedLines (T3.s2 (T4.s3 s4res)) = T2.totalClearedLines s2o)
    by (rewrite Etc; reflexivity).
  assert (Hc2res : T2.Correct (T3.s2 (T4.s3 s4res))). {
    unfold T2.Correct; split.
    - exact Hc1res.
    - unfold T2.LevelCorrect; rewrite Elv', Etc'; exact HLv.
  }
  (* T3.Correct: hold/swapped copied unchanged from s3o by UnchangedT3Part;
   * gameover likewise copied all the way from s1o (Ego1), so
   * GameoverImplyNotSwapped reduces to the same proposition as at s3o. *)
  assert (Eh' : T3.hold (T4.s3 s4res) = T3.hold s3o) by (rewrite Eh; reflexivity).
  assert (Esw' : T3.swapped (T4.s3 s4res) = T3.swapped s3o) by (rewrite Esw; reflexivity).
  assert (Ego3 : T3.gameover (T4.s3 s4res) = T3.gameover s3o)
    by (unfold T3.gameover; rewrite Ego1; reflexivity).
  assert (Hc3res : T3.Correct (T4.s3 s4res)). {
    unfold T3.Correct; split; [ | split ].
    - exact Hc2res.
    - unfold T3.SwappedImplyHoldSome; rewrite Esw', Eh'; exact HSw.
    - unfold T3.GameoverImplyNotSwapped; rewrite Ego3, Esw'; exact HGoNS.
  }
  (* T4.Correct: the Draw is untouched by rotation, copied through Ed. *)
  assert (Ed' : T4.d s4res = T4.d s4o) by (rewrite Ed; reflexivity).
  assert (Hc4res : T4.Correct s4res). {
    unfold T4.Correct; split.
    - exact Hc3res.
    - rewrite Ed'; exact HCD.
  }
  (* Finally, T5.Correct s': T4.Correct via Es4, LowestShadowY recomputed
   * fresh — vacuous when gameover, else established by ShadowYSpec, exactly
   * as for every other T4-forwarded T5 event. *)
  unfold T5.Correct; split_top.
  - rewrite Es4; exact Hc4res.
  - unfold T5.LowestShadowY; intros Hgo.
    assert (Hgo' : T4.gameover s4res = false)
      by (unfold T5.gameover in Hgo; rewrite Es4 in Hgo; exact Hgo).
    destruct (T5P.ShadowYSpec s4res Hc4res Hgo') as (H1 & H2 & H3 & H4).
    assert (Emg' : T5.mg s' = T4.mg s4res) by (unfold T5.mg; rewrite Es4; reflexivity).
    assert (Ep' : T5.p s' = T4.p s4res) by (unfold T5.p; rewrite Es4; reflexivity).
    assert (Epx' : T5.px s' = T4.px s4res) by (unfold T5.px; rewrite Es4; reflexivity).
    assert (Epr' : T5.pr s' = T4.pr s4res) by (unfold T5.pr; rewrite Es4; reflexivity).
    assert (Epy' : T5.py s' = T4.py s4res) by (unfold T5.py; rewrite Es4; reflexivity).
    unfold T5.ValidPieceCannotGoDown.
    rewrite Egy, Emg', Ep', Epx', Epr', Epy'.
    repeat split.
    + exact H1.
    + exact H2.
    + exact H3.
    + intros y Hy1 [Hy2 Hy3]; apply (H4 y Hy1 Hy2 Hy3).
  - apply (RotateKickBranchGyEqShadowY Hc Hn).
Qed.


(* ========================================================================= *)
(* State invariants                                                          *)
(* ========================================================================= *)

Lemma InitCorrect : ∀ (bags : ℕ → ℕ → T1.Piece) (H : ∀ i, T4.PieceSet (bags i)),
  Correct (Init bags H).
Proof.
  intros bags H; unfold Correct, Init; apply T5P.InitCorrect.
Qed.

Lemma NextCorrect : ∀ [e : Event] [s s' : State]
  (Hc : Correct s)
  (Hn : Next e s = Some s'),
  Correct s'.
Proof.
  intros e s s' Hc Hn.
  unfold Correct in *.
  destruct e as [e5 | cw].
  - (* forwarded T5 event *)
    unfold Next, NextT5Event in Hn.
    eapp T5P.NextCorrect.
  - (* RotateKick: guard, then whichever shift succeeded (left, else right) *)
    unfold Next, RotateKickPiece in Hn; cbv zeta in Hn.
    destruct (! T5.gameover s &&
              ! match T5.RotatePiece cw s with Some _ => true | None => false end)
      eqn: Eg; [ | discriminate Hn ].
    destruct (T5.RotatePiece cw (T5.NewPieceYXState (T5.py s, T5.px s - 1) s))
      as [r |] eqn: El.
    + (* left succeeded: Hn collapses to Some r = Some s' *)
      assert (Er : r = s') by (inject Hn; auto).
      rewrite Er in El.
      eapp RotateKickBranchCorrect.
    + (* left failed: Hn collapses to the right-shift call directly *)
      eapp RotateKickBranchCorrect.
Qed.

Lemma RotateKickPieceCorrectWithoutGameover : ∀ [s s' cw]
  (Hc : CorrectWithoutGameover s)
  (Hn : RotateKickPiece cw s = Some s'),
  CorrectWithoutGameover s'.
Proof.
  intros.
  unfold RotateKickPiece in Hn; cbv zeta in Hn.
  destruct (! T5.gameover s &&
            ! match T5.RotatePiece cw s with Some _ => true | None => false end)
    eqn: Eg; [ | discriminate Hn ].
  destruct (T5.RotatePiece cw (T5.NewPieceYXState (T5.py s, T5.px s - 1) s))
    as [r |] eqn: El.
  - assert (Er : r = s') by (inject Hn; auto).
    rewrite Er in El.
    assert (Hres : T5.CorrectWithoutGameover s' ∧ T5.mg s' = T5.mg s ∧ T5.gameover s' = T5.gameover s)
      by (eapply RotateKickBranchCorrectWithoutGameover; eassumption).
    exact (proj1 Hres).
  - assert (Hres : T5.CorrectWithoutGameover s' ∧ T5.mg s' = T5.mg s ∧ T5.gameover s' = T5.gameover s)
      by (eapply RotateKickBranchCorrectWithoutGameover; eassumption).
    exact (proj1 Hres).
Qed.

Lemma RotateKickPieceMgGameoverUnchanged : ∀ [s s' cw]
  (Hc : CorrectWithoutGameover s)
  (Hn : RotateKickPiece cw s = Some s'),
  mg s' = mg s ∧ gameover s' = gameover s.
Proof.
  intros.
  unfold RotateKickPiece in Hn; cbv zeta in Hn.
  destruct (! T5.gameover s &&
            ! match T5.RotatePiece cw s with Some _ => true | None => false end)
    eqn: Eg; [ | discriminate Hn ].
  destruct (T5.RotatePiece cw (T5.NewPieceYXState (T5.py s, T5.px s - 1) s))
    as [r |] eqn: El.
  - assert (Er : r = s') by (inject Hn; auto).
    rewrite Er in El.
    assert (Hres : T5.CorrectWithoutGameover s' ∧ T5.mg s' = T5.mg s ∧ T5.gameover s' = T5.gameover s)
      by (eapply RotateKickBranchCorrectWithoutGameover; eassumption).
    exact (proj2 Hres).
  - assert (Hres : T5.CorrectWithoutGameover s' ∧ T5.mg s' = T5.mg s ∧ T5.gameover s' = T5.gameover s)
      by (eapply RotateKickBranchCorrectWithoutGameover; eassumption).
    exact (proj2 Hres).
Qed.

Theorem SpecCorrect : ∀ e s s',
    (∀ bags H, Correct (Init bags H))
  ∧ (Correct s → Next e s = Some s' → Correct s').
Proof. split; eauto using InitCorrect, NextCorrect. Qed.


(* ========================================================================= *)
(* Step invariants                                                           *)
(* ========================================================================= *)

Theorem CorrectStepHolds : ∀ s s'
  (Hc : Correct s),
  CorrectStep s s'.
Proof.
  intros.
  set (s3 := T4.s3 (T5.s4 (s5 s))).
  set (s3' := T4.s3 (T5.s4 (s5 s'))).
  set (s2 := T3.s2 s3).
  set (s2' := T3.s2 s3').
  enough (T2.NonDecreasingScore s2 s2' ∧ T2.NonDecreasingLevel s2 s2' ∧
      T2.ScoreRisesOnClear s2 s2' ∧ T3.HoldMonotone s3 s3')
    by now unfold CorrectStep, T5.CorrectStep, T4.CorrectStep, T3.CorrectStep, T2.CorrectStep.
  assert (Hc2 : T2.Correct s2)
    by now unfold Correct, T5.Correct, T4.Correct, T3.Correct in Hc; tauto.
  assert (L1 : T2.NonDecreasingScore s2 s2') by now apply (T2P.StepNonDecreasingScore s2 s2').
  assert (L2 : T2.NonDecreasingLevel s2 s2') by now apply (T2P.StepNonDecreasingLevel s2' Hc2).
  assert (L3 : T2.ScoreRisesOnClear s2 s2') by now apply (T2P.StepScoreRisesOnClear s2 s2').
  assert (L4 : T3.HoldMonotone s3 s3') by now apply (T3P.StepHoldMonotone s3 s3').
  split_top; auto using L1, L2, L3, L4.
Qed.


(* ========================================================================= *)
(* Refinement                                                                *)
(* ========================================================================= *)

Lemma InitRefine : ∀ bags HSet, fₛ (T6.Init bags HSet) = T5.Init bags HSet.
Proof. intros; reflexivity. Qed.

(*
         e5
   s5    →    s5'
fₛ ↑     ⇑fₑ  ↑ fₛ
   s6    →    s6'
         e5
*)

Lemma NextRefine : ∀ e5 s6 s6'
  (H1 : NextT5Event e5 s6 = Some s6'),
  T6.NextT5Event (fₑ e5) (fₛ s6) = Some (fₛ s6').
Proof.
  intros e5 s6 s6' H1; unfold fₑ, fₛ, id; exact H1.
Qed.

Theorem T6RefinesT5Holds : T6RefinesT5.
Proof. split; auto using InitRefine, NextRefine. Qed.


(* ========================================================================= *)
(* Helpers for refining models                                               *)
(* ========================================================================= *)

Lemma RotateKickNotGameover : ∀ [s s' cw]
  (H1 : RotateKickPiece cw s = Some s'),
  gameover s = false.
Proof.
  intros.
  unfold RotateKickPiece in H1; cbv zeta in H1.
  destruct (! gameover s &&
    ! match T5.RotatePiece cw s with Some _ => true | None => false end) eqn: E.
  - apply andb_true_iff in E as [E1 _]; now apply negb_true_iff in E1.
  - unfold gameover in E; rewrite E in H1; discriminate H1.
Qed.