name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      rocq: ${{ steps.filter.outputs.rocq }}
      js: ${{ steps.filter.outputs.js }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'ci/Dockerfile'
              - 'ci/VERSION'
            rocq:
              - '**/*.v'
              - '**/dune-project'
              - '**/dune'
            js:
              - 'js/**/*.js'
              - 'js/package.json'
              - 'js/package-lock.json'

  build-image:
    needs: changes
    if: needs.changes.outputs.docker == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Dockerfile version
        id: version
        run: echo "value=$(cat ci/VERSION)" >> "$GITHUB_OUTPUT"

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/setup-buildx-action@v3

      - name: Push Docker image to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: ci
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/formal-tetris-ci:${{ steps.version.outputs.value }}
            ghcr.io/${{ github.repository }}/formal-tetris-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  check-proofs:
    needs: [changes, build-image]
    # Below, `always()` is needed to avoid this step to be skipped if
    # `build-image` didn't trigger.
    if: always() && needs.changes.outputs.rocq == 'true' && needs.build-image.result != 'failure'
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/formal-tetris-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root # Override rocq user: non-root users make the checkout fail
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add opam switch to PATH
        run: echo "$(opam var --root=/home/rocq/.opam bin)" >> "$GITHUB_PATH"

      - name: Check proofs
        run: dune build --display=progress --action-stdout-on-success=swallow --action-stderr-on-success=must-be-empty

  run-js-tests:
    needs: [changes, build-image]
    if: always() && needs.changes.outputs.js == 'true' && needs.build-image.result != 'failure'
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/formal-tetris-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run JS tests
        run: |
          cd js/
          npm install
          npm test
